#!/bin/bash

# make line just for testing purpose
make

cd tests/

for i in "$@"
do
	# echo "$i"
	# echo "$ioutput.txt"m
	string=""
	string+="$i"
	string+="_output.txt"
	echo "$string"
	../banksys ../teststate.txt "$string" < $i 
done
