#!/bin/bash


cd tests/

for i in 1
do
	echo "checking output of test $i"
	rm diffresult.txt
	diff output1.txt expected1.txt > diffresult.txt
	if [ -s diffresult.txt ]
		then
			echo "Test Fail"
		else
			echo "Test Success"
	fi
done
